# Generated by Django 5.2.16 on 2026-09-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pessoa', 'Pessoa'), ('pessoas', 'Pessoas'), ('interesse', 'Ponto de interesse')], max_length=32)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('color', models.CharField(choices=[('red', 'Vermelho'), ('amber', 'Âmbar'), ('green', 'Verde'), ('cyan', 'Ciano'), ('violet', 'Violeta'), ('slate', 'Ardósia')], default='slate', max_length=16)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
